amazebytrain/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('orders.urls')),
]

orders/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

handler404 = 'orders.views.Error404View'

urlpatterns = [
    url(r'^$', views.HomepageView.as_view(), name='home'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^book/$', views.BookView.as_view(), name='book'),
    url(r'^go/$', views.LoadingView.as_view(), name='loading'),
    url(r'^payment/minimum/$', views.minimum, name='minimum'),
    url(r'^payment/authorise/$', views.authorise, name='authorise'),
    url(r'^payment/charge/(?P<paymentmethod>[a-z0-9]+)/$', views.charge, name='charge'),
    url(r'^order/(?P<transaction_id>[A-Za-z0-9\-]+)/$', views.order, name='order'),
]

orders/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

import uuid

class Order(models.Model):
    # each individual status
    CREATED = 0
    SUBMITTED = 1
    PROCESSED = 2
    PROVISIONED = 3
    CANCELLED = 4

    # set of possible order statuses
    ORDER_STATUSES = (
        (CREATED, 'Created'),
        (SUBMITTED, 'Submitted'),
        (PROCESSED, 'Processed'),
        (PROVISIONED, 'Provisioned'),
        (CANCELLED, 'Cancelled'),
    )

    # set of possible payment gateways
    PAYMENT_GATEWAYS = (
        ("manual", "Other"),
        ("stripe", "Stripe"),
        ("gocardless", "GoCardless"),
        ("paypal", "PayPal")
    )

    transaction_id = models.UUIDField(_("transaction ID"), primary_key=True, editable=True, default=uuid.uuid4)
    payment_gateway = models.CharField(_("payment gateway"), max_length=50, choices=PAYMENT_GATEWAYS, default="manual")
    gateway_order_id = models.CharField(_("gateway order ID"), max_length=255, blank=True)
    gateway_description = models.CharField(_("payment method"), max_length=255, blank=True)
    payment_token = models.CharField(_("payment token"), max_length=255, blank=True)

    status = models.PositiveIntegerField(_("status"), choices=ORDER_STATUSES, default=SUBMITTED)
    paid = models.BooleanField(_("paid"), default=False)
    ip_address = models.GenericIPAddressField(_("IP address"), default="::1")
    created = models.DateTimeField(_("created"), auto_now_add=True)
    last_updated = models.DateTimeField(_("last updated"), auto_now=True)
    tracked = models.BooleanField(_("tracked"), default=False)

    # Contact information
    name = models.TextField(_("name"))
    email = models.EmailField(_("email"))

    def __unicode__(self):
        return "Order {0}".format(self.transaction_id)

    @models.permalink
    def get_absolute_url(self):
        return ('order', None, {'transaction_id': self.transaction_id})

    @property
    def total(self):
        items = self.passenger_set.all()
        total = 0
        for item in items:
            total += item.price

        return total

    @property
    def qty(self):
        return self.passenger_set.count()

    class Meta:
        ordering = ('-last_updated',)

class Passenger(models.Model):
    TICKET_TYPES = (
        ("shared", "Shared compartment"),
        ("wheelchair", "Wheelchair accessible"),
        ("double", "Double room"),
        ("single", "Single room")
    )

    order = models.ForeignKey(Order, null=True) # XXX: make non nullable
    name = models.TextField(_("name"))
    email = models.EmailField(_("email"))
    passport_name = models.TextField(_("name on passport"))
    mobile = models.CharField(_("mobile phone number"), max_length=20)
    price = models.DecimalField(_("price"), max_digits=19, decimal_places=2)
    ticket_type = models.CharField(_("ticket type"), max_length=20, choices=TICKET_TYPES)
    notes = models.TextField(blank=True)

    created = models.DateTimeField(_("created"), auto_now_add=True)
    last_updated = models.DateTimeField(_("last updated"), auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('-last_updated',)

orders/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

class BookingForm(forms.Form):
    PAYMENT_GATEWAYS = (
        ("directdebit", "Direct Debit"),
        ("creditcard", "Credit/Debit Card"),
        ("paypal", "PayPal")
    )

    name = forms.CharField(label=_("real name"))
    email = forms.EmailField(label=_("email"))
    payment_gateway = forms.ChoiceField(label=_("payment method"), choices=PAYMENT_GATEWAYS)
    price = forms.DecimalField(decimal_places=2)
    coc = forms.BooleanField(label=_("code of conduct agreement"))
    token = forms.CharField(label=_("stripe token"), required=False)

class PassengerForm(forms.Form):
    TICKET_TYPES = (
        ("shared", "Shared compartment"),
        ("wheelchair", "Wheelchair accessible"),
        ("double", "Double room"),
        ("single", "Single room")
    )

    idx = forms.CharField(label=_("index"))
    real_name = forms.CharField(label=_("real name"))
    passport_name = forms.CharField(label=_("name on passport"))
    mobile = forms.CharField(label=_("mobile phone number"))
    room = forms.ChoiceField(label=_("ticket type"), choices=TICKET_TYPES)
    other_requirements = forms.CharField(required=False, widget=forms.Textarea)

orders/views.py
# coding: utf-8

from __future__ import absolute_import

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.decorators.http import require_POST
from django.forms import formset_factory
from django.conf import settings
from django.contrib import messages
from django.core.cache import cache

from orders import forms, models, context_processors

from decimal import Decimal

import json
import uuid
import stripe
import paypalrestsdk

stripe.api_key = settings.STRIPE_SECRET_KEY

paypalrestsdk.configure({
    "mode": settings.PAYMENT_ENVIRONMENT,
    "client_id": settings.PAYPAL_CLIENT_ID,
    "client_secret": settings.PAYPAL_CLIENT_SECRET
})

def find_where(iterable, dct):
    # http://stackoverflow.com/questions/23553060/emulating-the-behavior-of-findwhere-in-python
    for item in iterable:
        if all(item[key] == value for key, value in dct.items()):
            yield item

def minimum(request):
    return HttpResponse(json.dumps(context_processors.minimum_price(request)), content_type="application/json")

def order(request, transaction_id):
    order = get_object_or_404(models.Order, transaction_id=transaction_id)

    if request.user.is_staff:
        return render(request, "order_view.html", {'order': order})
    elif request.method == "GET" and order.tracked == False:
        order.tracked = True
        order.save()
        return render(request, "order_view.html", {'order': order})
    elif request.method == "POST":
        if order.email == request.POST.get("email"):
            order.tracked = False
            order.save()
        else:
            messages.error(request, "Please re-enter the email address.")
        return redirect("order", transaction_id=transaction_id)
    else:
        return render(request, "order_verify.html")

@require_POST
def authorise(request):
    form_data = {
        "name": request.POST.get("contact_name"),
        "email": request.POST.get("email"),
        "payment_gateway": request.POST.get("payment_gateway"),
        "price": request.POST.get("price"),
        "coc": (request.POST.get("coc") == "1"),
        "token": request.POST.get("stripeToken")
    }

    passenger_data = json.loads(request.POST.get("passengers"))

    formset_data = {
        "form-TOTAL_FORMS": len(passenger_data),
        "form-INITIAL_FORMS": "0",
        "form-MIN_NUM_FORMS": "1",
        "form-MAX_NUM_FORMS": ""
    }

    for index, passenger in enumerate(passenger_data):
        for key, value in passenger.iteritems():
            formset_data["form-" + str(index) + "-" + key] = value

    # Instantiate the forms
    booking_form = forms.BookingForm(form_data)
    formset = formset_factory(forms.PassengerForm, min_num=1, validate_min=3)

    passenger_forms = formset(formset_data)

    if booking_form.is_valid() and passenger_forms.is_valid():
        # Get price
        price = Decimal(booking_form.cleaned_data["price"])
        minimum_price = Decimal(context_processors.minimum_price(request)["minimum_price"] * len(passenger_data))

        # Check if it's the minimum
        if price < minimum_price:
            messages.warning(request, "The minimum price for this transaction is £" + str(minimum_price) + ".")
            return redirect("book")

        # Add booking fees
        if list(find_where(passenger_data, {"room": "single"})) != []:
            booking_fee = Decimal("30")
        elif list(find_where(passenger_data, {"room": "double"})) != []:
            booking_fee = Decimal("15")
        else:
            booking_fee = Decimal("0")

        price = price + booking_fee

        # Create the order object and populate with some data
        order = models.Order()
        order.name = booking_form.cleaned_data["name"]
        order.email = booking_form.cleaned_data["email"]

        # authorise (or in the case of Stripe, charge) the transaction
        if booking_form.cleaned_data["payment_gateway"] == "creditcard":
            order.payment_gateway = "stripe"
            paid = False
            token = booking_form.cleaned_data.get("token")

            if token:
                try:
                    charge = stripe.Charge.create(
                        amount=int(price * 100),
                        currency="gbp",
                        card=token,
                        idempotency_key=token,
                        description="A MAZE By Train Booking",
                        receipt_email=order.email)
                    paid = True
                except stripe.error.CardError, e:
                    messages.error(request, e.message)
                    paid = False
                    redirect_url = redirect("book")
            else:
                messages.error(request, "Couldn't get the payment token. Your card was not charged.")
                redirect_url = redirect("book")

            if paid:
                order.gateway_order_id = charge.id
                order.status = order.PROVISIONED
                order.gateway_description = charge.source.brand + " *" + charge.source.last4
                order.paid = True

                # Save the order information
                order.save()
                messages.success(request, "Thank you for supporting us! You will receive an email soon with further information about the journey you'll be taking with us.")
                redirect_url = redirect("order", transaction_id=order.transaction_id)

        if booking_form.cleaned_data["payment_gateway"] == "paypal":
            payment = paypalrestsdk.Payment({
                "intent": "sale",
                "redirect_urls": {
                    "return_url": settings.SITE_URL + "/payment/charge/paypal/",
                    "cancel_url": settings.SITE_URL + "/book/"
                },
                "payer": {
                    "payment_method": "paypal"
                },
                "transactions": [
                    {
                        "amount": {
                            "total": str(price),
                            "currency": "GBP"
                        },
                        "description": "A MAZE By Train Booking"
                    }
                ]
            })

            if payment.create():
                order.payment_gateway = "paypal"
                order.payment_token = payment["id"]
                order.status = order.SUBMITTED
                order.save()

                approval_url = (url for url in payment["links"] if url["rel"] == "approval_url").next()
                redirect_url = redirect(approval_url["href"])
                paid = True
            else:
                messages.error(request, "We weren't able to connect to PayPal. Please try again.")
                redirect_url = redirect("book")
                paid = False

        # Add the passengers
        if paid:
            passenger_price = price / Decimal(len(passenger_forms.cleaned_data))

            for passenger_form in passenger_forms.cleaned_data:
                passenger = models.Passenger()
                passenger.order = order
                passenger.name = passenger_form["real_name"]
                passenger.passport_name = passenger_form["passport_name"]
                passenger.email = booking_form.cleaned_data["email"]
                passenger.mobile = passenger_form["mobile"]
                passenger.ticket_type = passenger_form["room"]
                passenger.notes = passenger_form["other_requirements"]
                passenger.price = passenger_price

                # Save the passenger info
                passenger.save()

            # Clear minimum price cache
            cache.delete("abt_minimum_price")
    else:
        for field, errors in booking_form.errors.iteritems():
            messages.warning(request, (getattr(booking_form.fields[field], "label") or field).capitalize() + ": " + " ".join(list(errors)))

        passenger_form_fields = forms.PassengerForm().fields

        for form_errors in passenger_forms.errors:
            for field, errors in form_errors:
                messages.warning(request, (getattr(passenger_form_fields[field], "label") or field).capitalize() + ": " + " ".join(list(errors)))

        redirect_url = redirect("book")

    return redirect_url

def charge(request, paymentmethod):
    redirect_url = redirect("book")

    if paymentmethod == "paypal":
        payment_id = request.GET.get("paymentId")
        payer_id = request.GET.get("PayerID")

        order = get_object_or_404(models.Order, payment_token=payment_id)
        payment = paypalrestsdk.Payment.find(payment_id)

        # Execute the payment
        if payment.execute({"payer_id": payer_id}):
            order.status = models.Order.PROVISIONED
            order.save()
            messages.success(request, "Thank you for supporting us! You will receive an email soon with further information about the journey you'll be taking with us.")
            redirect_url = redirect("order", transaction_id=order.transaction_id)
        else:
            order.delete()
            messages.error(request, payment.error)

    return redirect_url

class HomepageView(TemplateView):
    template_name = "homepage.html"

class ContactView(TemplateView):
    template_name = "contact.html"

class BookView(TemplateView):
    template_name = "book.html"

    def get_context_data(self, **kwargs):
        context = super(BookView, self).get_context_data(**kwargs)
        context['STRIPE_PUBLISHABLE_KEY'] = settings.STRIPE_PUBLISHABLE_KEY
        return context

class Error404View(TemplateView):
    template_name = "404.html"

class LoadingView(TemplateView):
    template_name = "loading.html"

orders/templates/base.html
{% load staticfiles %}<!DOCTYPE html>

<html lang="en-gb" data-minimum-price="{{ minimum_price }}">

<head>
    <meta charset="utf-8">
    <title>{% block htmltitle %}A&nbsp;MAZE BY TRAIN{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500,900italic,300,500italic,300italic,900">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script defer src="https://cdn.jsdelivr.net/jquery/2.1.4/jquery.min.js" crossorigin="anonymous" integrity="sha256-ImQvICV38LovIsvla2zykaCTdEh1Z801Y+DSop91wMU="></script>
    <script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
</head>

<body>

<div class="container">

<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="{% block nav_homepage %}{% endblock %}">
                <a href="{% url 'home' %}">The Adventure.</a>
            </li>
            <li class="{% block nav_book %}{% endblock %}">
                <a href="{% url 'book' %}">Book Now.</a>
            </li>
            <li class="{% block nav_contact %}{% endblock %}">
                <a href="{% url 'contact' %}">Contact Me.</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="https://twitter.com/amazebytrain" title="Twitter"><i class="fa fa-twitter"></i> Twitter.</a></li>
            <li><a href="https://instagram.com/amazebytrain" title="Instagram"><i class="fa fa-instagram"></i> Instagram.</a></li>
        </ul>
    </div>
</nav>

{% block heading %}{% endblock %}

{% block messages %}
<div class="col-md-12">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.level_tag }} {{ message.tags }}" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i class="fa fa-times-circle"></i></span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
</div>
{% endblock %}

{% block body %}{% endblock %}

{% block footer %}{% endblock %}

</div>

</body>

</html>

orders/templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block nav_contact %}active{% endblock %}

{% block heading %}

<section class="logo berlin">
    <h1><strong>Contact</strong> Me.</h1>

    <p>Send me an email at <a href="mailto:info@amazebytrain.com">info@amazebytrain.com</a> if you have any questions or need any help.</p>

    <p><em><strong>A&nbsp;MAZE</strong> By Train is organised by <a href="http://jonathanprior.com/">Jonathan Prior</a>.</em></p>
</section>

{% endblock %}

orders/templates/homepage.html
{% extends "base.html" %}
{% load staticfiles %}

{% block nav_homepage %}active{% endblock %}

{% block heading %}
<section class="logo cologne">
    <h1><strong>A&nbsp;MAZE</strong> By Train.</h1>
    <h2 class="visible-sm-block visible-xs-block visible-md-inline visible-lg-inline">
        London to Berlin.
    </h2>
    <h2 class="visible-sm-block visible-xs-block visible-md-inline visible-lg-inline">
        18<small>th</small> and 24<small>th</small> April 2016.
    </h2>
</section>
{% endblock %}

{% block body %}
<section class="body col-md-6">
    <h1><strong>A&nbsp;MAZE</strong> By Train Returns.</h1>
    <p><em><strong>A&nbsp;MAZE</strong> By Train</em> is a group of people travelling from London to <a href="http://amaze-berlin.de/" title="A MAZE."><strong>A&nbsp;MAZE.</strong> / Berlin 2016</a>, taking trains all the way.</p>
    <p>After the resounding success of <a href="https://2015.amazebytrain.com/"><em><strong>A&nbsp;MAZE</strong> By Train</em> in 2015</a>, we're doing it again. This time, with an improved route, arriving at a sensible time of the morning, and better accommodation.</p>
    <p><img src="{% static 'images/thesign.jpg' %}" class="img-responsive" role="presentation"></p>
</section>

<section class="body col-md-6">
    <h1><strong>The</strong> Route.</h1>
    <p>Starting from <strong>London St. Pancras International</strong>, around lunchtime, you'll travel with us to <strong>Brussels</strong>, arriving mid-afternoon.</p>
    <p>From Brussels, we'll travel to Germany. In Germany, we'll find some time to sit and have dinner, and then we'll get on a sleeper train to <strong>Berlin</strong>, arriving at around <strong>7:00am</strong>.</p>
    <p>For the journey back to London, we'll leave in the morning, and take day trains back to London, arriving in the evening.</p>
</section>

<section class="body col-md-6">
    <h1><strong>Accommodation</strong>.</h1>
    <p>Standard sleeper accommodation during <em><strong>A MAZE</strong> By Train</em> consists of a 3-4 bed compartment. Single and double rooms are available for an additional fee.</p>
    <p>Wheelchair accessible travel is available at no extra cost. If you have any other accessibility needs, please let us know and we'll make arrangements.</p>
</section>
{% endblock %}

orders/templates/loading.html
{% load staticfiles %}<!DOCTYPE html>
{% url request.GET.to as to %}
<html lang="en-gb">

<head>
    <meta charset="utf-8">
    <title>Loading...</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500,900italic,300,500italic,300italic,900">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% if to %}
    <noscript><meta http-equiv="refresh" content="1; url={{ to }}"></noscript>
    {% endif %}
</head>

<body>

<h1 class="text-center sr-only">Loading</h1>

<h2 class="text-center">
    <span class="pulser first"></span><span class="pulser second"></span><span class="pulser third"></span>
</h2>

<script>
(function (top, self, location) {
    "use strict";

    var qs = function (name) {
        var regexS, regex, results;
        name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
        regexS = "[\\?&]" + name + "=([^&#]*)";
        regex = new RegExp(regexS);
        results = regex.exec(location.href);
        if (results === null) {
            return "";
        } else {
            return results[1];
        }
    }

    if (top !== self) {
        top.location.replace(location);
    } else {
        if (qs("to") !== "") {
            setTimeout("location.replace('{{ to }}')", 1000);
        }
    }
}(window.top, window.self, window.location));
</script>
</body>

</html>

orders/templates/order_verify.html
{% extends "base.html" %}
{% load staticfiles %}

{% block nav_book %}active{% endblock %}

{% block heading %}
<h1 class="col-md-12"><strong>Your</strong> Order.</h1>
{% endblock %}

{% block body %}
<div class="col-md-12">
<p class="lead">Please enter your email address, so we can make sure it's you.</p>
</div>

<div class="col-md-offset-1 col-md-10">
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}

        <div class="form-group form-group-lg">
            <label for="email" class="col-sm-2 control-label">Email address</label>
            <div class="col-sm-10">
                <input type="email" name="email" class="form-control" id="email" placeholder="Email">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary btn-lg">Show order</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

orders/templates/order_view.html
{% extends "base.html" %}
{% load staticfiles %}

{% block nav_book %}active{% endblock %}

{% block heading %}
<h1 class="print-logo col-md-12 visible-print-block"><strong>A MAZE</strong> By Train.</h1>
<h1 class="col-md-12"><strong>Your</strong> Order.</h1>
{% endblock %}

{% block body %}
<div class="col-md-12">
<h2><strong>Payment</strong> Information.</h2>

<dl class="dl-horizontal">
    <dt>Transaction ID</dt>
    <dd>{{ order.transaction_id|upper }}</dd>
    <dt>Payment method</dt>
    <dd>{{ order.gateway_description|default:order.get_payment_gateway_display }}</dd>
    <dt>Order date</dt>
    <dd>{{ order.created|date:"r" }}</dd>
    <dt>Total charged</dt>
    <dd>£{{ order.total }}</dd>
    <dt>Contact name</dt>
    <dd>{{ order.name }}</dd>
    <dt>Contact email</dt>
    <dd>{{ order.email }}</dd>
</dl>

<h2><strong>The</strong> Passengers.</h2>

{% for passenger in order.passenger_set.all %}
<h3>{{ passenger.name }}</h3>

<dl class="dl-horizontal">
    <dt>Name on passport</dt>
    <dd>{{ passenger.passport_name|upper }}</dd>
    <dt>Mobile number</dt>
    <dd>{{ passenger.mobile }}</dd>
    <dt>Accommodation</dt>
    <dd>{{ passenger.get_ticket_type_display }}</dd>
    <dt>Other requirements</dt>
    <dd>{{ passenger.notes }}</dd>
</dl>

<div class="clearfix"></div>
{% endfor %}
</div>

<script>
window.sessionStorage.clear();
</script>
{% endblock %}